sudo: required
services:
  - docker

before_install:
  -  docker build -t wgfm/docker-react-test -f Dockerfile.dev .

script:
  - docker run -e CI=true wgfm/docker-react-test npm run test -- --coverage